ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO developer;

ALTER ROLE developer WITH PASSWORD

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO developer;

CREATE ROLE fer_integration_service WITH PASSWORD 'q@3iL]Vq%6dv' LOGIN;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON ALL TABLES TO fer_integration_service;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO fer_integration_service;